name: Keep Supabase Alive

on:
  schedule:
    - cron: "45 19 * * *" # Runs at 7:45 PM UTC daily
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install @supabase/supabase-js
        
      - name: Run keep-alive script
        run: node .github/scripts/keep-alive.js 